### PR TITLE
String cleanup

### PR DESCRIPTION
**Pull request by thrasibule**
Got rid of the compatibility wrapper.
C++ strings where converted to C strings via c_str(), then converted back to python objects. But cython supports std::string natively via libcpp.string.

### CODE REVIEW

**Comment by dpinte** [comment]
LGTM

@phenaff This is mostly improvements due to the fact that we started the project with early versions of Cython (0.15 IIRC). You're ok with the changes?

**Comment by phenaff** [comment]
@dpinte Yes, this looks good, much simpler. But don't we still need the directive
# coding: utf-8
to make sure the string literals are utf-8?

**Comment by thrasibule** [comment]
I guess you might potentially need it if you have non ascii strings on input, but I don't think any of the quantlib functions take anything like that, do they? For python2, the only difference I noticed is that strings returned by functions show up as u"test" instead of "test" (type is unicode instead of str). They print the same though and comparisons work fine: u"test"=="test" is True for instance.
In python3 everything is same as before.

**Comment by dpinte** [comment]
Merging! This is a very good addition.

**Pull request merged**
