### PR TITLE
remove cpp extension for settings

### PR DESCRIPTION
**Pull request by thrasibule**
and expose more methods.

### CODE REVIEW

**Comment by dpinte** [comment]
@thrasibule this is a very interesting change. Any change you have tested it on Windows? There was/is an issue on Windows where the Setting singleton is not properly shared between extensions. Looking at your changes, it simplifies the old implementation and might also fix the problem. I'll try to test it asap on Windows if you did not.

**Comment by dpinte** [comment]
The failing test is related to the removed code. It can be updated/removed safely!

**Comment by thrasibule** [comment]
@dpinte regarding windows, I haven't tested it. I have never set up the compilation on windows which seems a bit tricky, so if you have a usable set up, please try it out! I 've also updated test_cython_bug, tests should be green now.

**Comment by dpinte** [comment]
@thrasibule I am going to merge this. I don't have much time to test on  Windows now but I don't think this can make the situation worse than it was.

**Pull request merged**
